dist: xenial
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - gcc-snapshot
      - doxygen

install:
  - pip install --user conan cmake


script:
  - ls /usr/bin/gcc*
  - g++-9 --version
  - CXX=/usr/bin/g++-9 CC=/usr/bin/gcc-9 cmake -D ENABLE_COVERAGE:BOOL=TRUE . 
  - cmake --build . -- -j2 
  - ctest -j2
  - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-9



