dist: bionic
sudo: false
language: cpp


before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get -y install gcc-9 doxygen


install:
  - pip install --user conan cmake


script:
  - CXX=/usr/bin/gcc-9 CC=/usr/bin/g++-9 cmake -D ENABLE_COVERAGE:BOOL=TRUE . 
  - cmake --build . -- -j2 
  - ctest -j2
  - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-9



