dist: xenial
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ppa:ubuntu-toolchain-r/test
    packages:
      - gcc-9
      - doxygen

install:
  - pip install --user conan cmake


script:
  - CXX=/usr/bin/gcc-9 CC=/usr/bin/g++-9 cmake -D ENABLE_COVERAGE:BOOL=TRUE . 
  - cmake --build . -- -j2 
  - ctest -j2
  - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-9



